#pragma once

// Placeholders only. Copy to interbridge_dev_secrets.h and replace every
// value locally. Never commit that ignored file or share its private key.
#define INTERBRIDGE_DEV_WIFI_SSID "REPLACE_WITH_WIFI_SSID"
#define INTERBRIDGE_DEV_WIFI_PASSWORD "REPLACE_WITH_WIFI_PASSWORD"
#define INTERBRIDGE_DEV_AWS_ENDPOINT "REPLACE_WITH_AWS_IOT_ENDPOINT"
#define INTERBRIDGE_DEV_DEVICE_ID "REPLACE_WITH_UNIQUE_DEV_DEVICE_ID"
#define INTERBRIDGE_DEV_ROOT_CA_PEM "REPLACE_WITH_AMAZON_ROOT_CA_PEM"
#define INTERBRIDGE_DEV_CERTIFICATE_PEM "REPLACE_WITH_UNIQUE_DEV_CERTIFICATE_PEM"
#define INTERBRIDGE_DEV_PRIVATE_KEY_PEM "REPLACE_WITH_UNIQUE_DEV_PRIVATE_KEY_PEM"
