#pragma once

// Placeholders only, used by compile-only CI. For local credentials, use
// scripts/generate_dev_secrets_header.ps1; never hand-write multiline raw
// strings in macros and never commit the generated ignored header.
#define INTERBRIDGE_DEV_WIFI_SSID "REPLACE_WITH_WIFI_SSID"
#define INTERBRIDGE_DEV_WIFI_PASSWORD "REPLACE_WITH_WIFI_PASSWORD"
#define INTERBRIDGE_DEV_AWS_ENDPOINT "REPLACE_WITH_AWS_IOT_ENDPOINT"
#define INTERBRIDGE_DEV_DEVICE_ID "REPLACE_WITH_UNIQUE_DEV_DEVICE_ID"
#define INTERBRIDGE_DEV_ROOT_CA_PEM "REPLACE_WITH_AMAZON_ROOT_CA_PEM"
#define INTERBRIDGE_DEV_CERTIFICATE_PEM "REPLACE_WITH_UNIQUE_DEV_CERTIFICATE_PEM"
#define INTERBRIDGE_DEV_PRIVATE_KEY_PEM "REPLACE_WITH_UNIQUE_DEV_PRIVATE_KEY_PEM"
